### PR TITLE
add all my currently open sourced school projects

### PR DESCRIPTION
**Pull request by koallen**

### CODE REVIEW

**Comment by tanhauhau** [comment]
Thanks. can help fix the merge conflicts?

**Comment by koallen** [comment]
Hi, I think I cannot resolve merge conflicts since I don't have write permission to this repo. :)

**Comment by tanhauhau** [comment]
@koallen merge my master:latest into your PR branch, fix if any conflicts.

**Comment by koallen** [comment]
Oh, sorry I didn't realise you merged the pull request sent by @SuyashLakhotia. The conflicts should be resolved now.

**Pull request merged**
